### ISSUE TITLE
Remove automatic numbering of figures

### ISSUE THREAD

**Issue by jdblischak** [jdblischak/git-for-science#7]
On Authorea, the figures only display their caption. Thus we have labeled the figures how we want. However, when exported, LaTeX also adds automatically generated labels. This creates duplicate labels, and also labels S1 Figure as Figure 4.

**Comment by gvwilson** [comment]
No idea...

**Comment by jdblischak** [comment]
They explained how to remove the duplicated figure labels. However, there does not seem to be a way to disable to the automatic figure labeling. We want the 4th figure to be "S1 Figure", not Figure 4.

From Deyan at Authorea:


2. For your figures, I would suggest using the Authorea-styled labels, to get automatic labeling. For instance, you can change your caption from:

\textbf{Figure 2}

to
\label{fig:figurename}

which will avoid the double-label in the PDF export, will allow you to reference your figures via \ref{fig:figurename} and will also auto-create an Authorea "Fig. 2" text under the figure in HTML. As long as you use the \label command consistently, you will see good results.

**Comment by erdavenport** [comment]
I know this will go against the spirit of Authorea, but what if we had Fig S1 not incorporated into the main document? We could keep the figure legend with the other figure legends (which is just a text box right now), and we could include the figure in the repo, but when we actually submit it's a separate pdf from the main document? That would allow us to name it separately. Totally not in the spirit though so I feel confident this idea will be vetoed :)

**Comment by jdblischak** [comment]
This is not a bad idea. And we may need to resort to such a strategy.

One thing I am not sure about at the moment is if we even are allowed to have supplemental information. This is part of the Education collection, and not a primary research article. Thus I was thinking of just having it be Figure 4, and when we send it to them suggest the idea that it become a supplemental figure. Unfortunately it may not survive the review since we have already used so many words.

**Comment by jdblischak** [comment]
No more supplemental figures so no longer a problem.
